$ANSIBLE_VAULT;1.1;AES256
37333861663461356233363766336632306132383837316565633632613863663635366636623635
6530613666656637343539306230613461646237646562390a306339616530623837363937623663
62353938396230616438616164303534626538303466623066313233393262353832666563613034
3933303230616637630a366664393833386636306361343032653433613962343366323133343031
33393534376433353263316633663935383833396564663637316534323530613931646562656636
6666316533616663643233366234303738353065306133396563
